import type { Book } from "./book";

export const defaultBooks: Book[] = [
  {
    id: "1",
    title: "The Silent Patient",
    author: {
      id: "a1",
      firstName: "Alex",
      lastName: "Michaelides",
      nationality: "British-Cypriot",
      image: "https://api.dicebear.com/7.x/initials/svg?seed=Alex+Michaelides",
    },
    genre: "Psychological Thriller",
    pageCount: 336,
    cover: "https://covers.openlibrary.org/b/isbn/9781250301697-L.jpg",
    source: "Publisher XYZ",
  },
  {
    id: "2",
    title: "To Kill a Mockingbird",
    author: {
      id: "a2",
      firstName: "Harper",
      lastName: "Lee",
      nationality: "American",
      image: "https://api.dicebear.com/7.x/initials/svg?seed=Harper+Lee",
    },
    genre: "Classic",
    pageCount: 281,
    cover: "https://covers.openlibrary.org/b/isbn/9780061120084-L.jpg",
    source: "Publisher ABC",
  },
  {
    id: "3",
    title: "Dune",
    author: {
      id: "a3",
      firstName: "Frank",
      lastName: "Herbert",
      nationality: "American",
      image: "https://api.dicebear.com/7.x/initials/svg?seed=Frank+Herbert",
    },
    genre: "Science Fiction",
    pageCount: 412,
    cover: "https://covers.openlibrary.org/b/id/12623822-L.jpg",
    source: "Publisher DEF",
  },
  {
    id: "4",
    title: "The Hobbit",
    author: {
      id: "a4",
      firstName: "J.R.R.",
      lastName: "Tolkien",
      nationality: "British",
      image: "https://api.dicebear.com/7.x/initials/svg?seed=JRR+Tolkien",
    },
    genre: "Fantasy",
    pageCount: 310,
    cover: "https://ia800409.us.archive.org/view_archive.php?archive=/6/items/olcovers39/olcovers39-L.zip&file=394001-L.jpg",
    source: "Publisher GHI",
  },
  {
    id: "5",
    title: "The Girl with the Dragon Tattoo",
    author: {
      id: "a5",
      firstName: "Stieg",
      lastName: "Larsson",
      nationality: "Swedish",
      image: "https://api.dicebear.com/7.x/initials/svg?seed=Stieg+Larsson",
    },
    genre: "Crime Novel",
    pageCount: 465,
    cover: "https://covers.openlibrary.org/b/isbn/9780307269751-L.jpg",
    source: "Publisher JKL",
  },
  // {
  //   id: "6",
  //   title: "1984",
  //   author: {  
  //     id: "a6",
  //     firstName: "George",
  //     lastName: "Orwell",
  //     nationality: "British",
  //     image: "https://api.dicebear.com/7.x/initials/svg?seed=George+Orwell",
  //   },
  //   genre: "Dystopian",
  //   pageCount: 328,
  //   cover: "https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg",
  //   source: "Publisher MNO",
  // },
  // {
  //   id: "7",
  //   title: "Pride and Prejudice",
  //   author: {
  //     id: "a7",
  //     firstName: "Jane",
  //     lastName: "Austen",
  //     nationality: "British",
  //     image: "https://api.dicebear.com/7.x/initials/svg?seed=Jane+Austen",
  //   },
  //   genre: "Romance",
  //   pageCount: 279,
  //   cover: "https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg",
  //   source: "Publisher PQR",
  // },
  // {
  //   id: "8",
  //   title: "The Alchemist",
  //   author: {
  //     id: "a8",
  //     firstName: "Paulo",
  //     lastName: "Coelho",
  //     nationality: "Brazilian",
  //     image: "https://api.dicebear.com/7.x/initials/svg?seed=Paulo+Coelho",
  //   },
  //   genre: "Fantasy",
  //   pageCount: 208,
  //   cover: "https://covers.openlibrary.org/b/isbn/9780062315007-L.jpg",
  //   source: "Publisher STU",
  // },
  // {
  //   id: "9",
  //   title: "The Da Vinci Code",
  //   author: {
  //     id: "a9",
  //     firstName: "Dan",
  //     lastName: "Brown",
  //     nationality: "American",
  //     image: "https://api.dicebear.com/7.x/initials/svg?seed=Dan+Brown",
  //   },
  //   genre: "Mystery",
  //   pageCount: 489,
  //   cover: "https://covers.openlibrary.org/b/isbn/9780307474278-L.jpg",
  //   source: "Publisher VWX",
  // },
  // {
  //   id: "10",
  //   title: "The Great Gatsby",
  //   author: {
  //     id: "a10",
  //     firstName: "F. Scott",
  //     lastName: "Fitzgerald",
  //     nationality: "American",
  //     image: "https://api.dicebear.com/7.x/initials/svg?seed=FScott+Fitzgerald",
  //   },
  //   genre: "Classic",
  //   pageCount: 180,
  //   cover: "https://covers.openlibrary.org/b/isbn/9780743273565-L.jpg",
  //   source: "Publisher YZ",
  // },
];