import type { Book } from "./book";

export const defaultBooks: Book[] = [
  {
    id: "1",
    title: "The Silent Patient",
    author: {
      id: "a1",
      firstName: "Alex",
      lastName: "Michaelides",
      nationality: "British-Cypriot",
    },
    genre: "Psychological Thriller",
    pageCount: 336,
    cover: "https://example.com/covers/silent-patient.jpg",
    source: "Publisher XYZ",
  },
  {
    id: "2",
    title: "To Kill a Mockingbird",
    author: {
      id: "a2",
      firstName: "Harper",
      lastName: "Lee",
      nationality: "American",
    },
    genre: "Classic",
    pageCount: 281,
    cover: "https://example.com/covers/mockingbird.jpg",
    source: "Publisher ABC",
  },
  {
    id: "3",
    title: "Dune",
    author: {
      id: "a3",
      firstName: "Frank",
      lastName: "Herbert",
      nationality: "American",
    },
    genre: "Science Fiction",
    pageCount: 412,
    cover: "https://example.com/covers/dune.jpg",
    source: "Publisher DEF",
  },
  {
    id: "4",
    title: "The Hobbit",
    author: {
      id: "a4",
      firstName: "J.R.R.",
      lastName: "Tolkien",
      nationality: "British",
    },
    genre: "Fantasy",
    pageCount: 310,
    cover: "https://example.com/covers/hobbit.jpg",
    source: "Publisher GHI",
  },
  {
    id: "5",
    title: "The Girl with the Dragon Tattoo",
    author: {
      id: "a5",
      firstName: "Stieg",
      lastName: "Larsson",
      nationality: "Swedish",
    },
    genre: "Crime Novel",
    pageCount: 465,
    cover: "https://example.com/covers/dragon-tattoo.jpg",
    source: "Publisher JKL",
  },
  {
    id: "6",
    title: "1984",
    author: {
      id: "a6",
      firstName: "George",
      lastName: "Orwell",
      nationality: "British",
    },
    genre: "Dystopian",
    pageCount: 328,
    cover: "https://example.com/covers/1984.jpg",
    source: "Publisher MNO",
  },
  {
    id: "7",
    title: "Pride and Prejudice",
    author: {
      id: "a7",
      firstName: "Jane",
      lastName: "Austen",
      nationality: "British",
    },
    genre: "Romance",
    pageCount: 279,
    cover: "https://example.com/covers/pride-prejudice.jpg",
    source: "Publisher PQR",
  },
  {
    id: "8",
    title: "The Alchemist",
    author: {
      id: "a8",
      firstName: "Paulo",
      lastName: "Coelho",
      nationality: "Brazilian",
    },
    genre: "Fantasy",
    pageCount: 208,
    cover: "https://example.com/covers/alchemist.jpg",
    source: "Publisher STU",
  },
  {
    id: "9",
    title: "The Da Vinci Code",
    author: {
      id: "a9",
      firstName: "Dan",
      lastName: "Brown",
      nationality: "American",
    },
    genre: "Mystery",
    pageCount: 489,
    cover: "https://example.com/covers/da-vinci-code.jpg",
    source: "Publisher VWX",
  },
  {
    id: "10",
    title: "The Great Gatsby",
    author: {
      id: "a10",
      firstName: "F. Scott",
      lastName: "Fitzgerald",
      nationality: "American",
    },
    genre: "Classic",
    pageCount: 180,
    cover: "https://example.com/covers/great-gatsby.jpg",
    source: "Publisher YZ",
  },
];
