// convert-data.js
const { log } = require("console");
const fs = require("fs");
const path = require("path");

const jsonData = {
  books: [
    {
      id: "1",
      title: "The Silent Patient",
      author: {
        id: "a1",
        firstName: "The",
        lastName: "Patient",
        nationality: "American",
        image:
          "https://api.dicebear.com/7.x/initials/svg?seed=The+Silent+Patient",
      },
      genre: "Fantasy",
      pageCount: 250,
      cover: "https://covers.openlibrary.org/b/isbn/9781250301697-L.jpg",
      source: "Penguin",
      description:
        "A compelling story of fantasy with unforgettable characters and thrilling twists.",
    },
    {
      id: "2",
      title: "Where the Crawdads Sing",
      author: {
        id: "a2",
        firstName: "Where",
        lastName: "Sing",
        nationality: "British",
        image:
          "https://api.dicebear.com/7.x/initials/svg?seed=Where+the+Crawdads+Sing",
      },
      genre: "Science Fiction",
      pageCount: 251,
      cover: "https://covers.openlibrary.org/b/isbn/9780735219090-L.jpg",
      source: "HarperCollins",
      description:
        "A compelling story of science fiction with unforgettable characters and thrilling twists.",
    },
    {
      id: "3",
      title: "The Nightingale",
      author: {
        id: "a3",
        firstName: "The",
        lastName: "Nightingale",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=The+Nightingale",
      },
      genre: "Historical Fiction",
      pageCount: 252,
      cover: "https://covers.openlibrary.org/b/isbn/9781250080400-L.jpg",
      source: "Faber & Faber",
      description:
        "A compelling story of historical fiction with unforgettable characters and thrilling twists.",
    },
    {
      id: "4",
      title: "Educated",
      author: {
        id: "a4",
        firstName: "Educated",
        lastName: "Educated",
        nationality: "British",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Educated",
      },
      genre: "Romance",
      pageCount: 253,
      cover: "https://covers.openlibrary.org/b/isbn/9780399590504-L.jpg",
      source: "Vintage",
      description:
        "A compelling story of romance with unforgettable characters and thrilling twists.",
    },
    {
      id: "5",
      title: "Normal People",
      author: {
        id: "a5",
        firstName: "Normal",
        lastName: "People",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Normal+People",
      },
      genre: "Biography",
      pageCount: 254,
      cover: "https://covers.openlibrary.org/b/isbn/9781984822178-L.jpg",
      source: "Random House",
      description:
        "A compelling story of biography with unforgettable characters and thrilling twists.",
    },
    {
      id: "6",
      title: "The Vanishing Half",
      author: {
        id: "a6",
        firstName: "The",
        lastName: "Half",
        nationality: "British",
        image:
          "https://api.dicebear.com/7.x/initials/svg?seed=The+Vanishing+Half",
      },
      genre: "Memoir",
      pageCount: 255,
      cover: "https://covers.openlibrary.org/b/isbn/9780525536291-L.jpg",
      source: "Penguin",
      description:
        "A compelling story of memoir with unforgettable characters and thrilling twists.",
    },
    {
      id: "7",
      title: "Becoming",
      author: {
        id: "a7",
        firstName: "Becoming",
        lastName: "Becoming",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Becoming",
      },
      genre: "Horror",
      pageCount: 256,
      cover: "https://covers.openlibrary.org/b/isbn/9781524763138-L.jpg",
      source: "HarperCollins",
      description:
        "A compelling story of horror with unforgettable characters and thrilling twists.",
    },
    {
      id: "8",
      title: "The Testaments",
      author: {
        id: "a8",
        firstName: "The",
        lastName: "Testaments",
        nationality: "British",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=The+Testaments",
      },
      genre: "Thriller",
      pageCount: 257,
      cover: "https://covers.openlibrary.org/b/isbn/9780385543781-L.jpg",
      source: "Faber & Faber",
      description:
        "A compelling story of thriller with unforgettable characters and thrilling twists.",
    },
    {
      id: "9",
      title: "The Goldfinch",
      author: {
        id: "a9",
        firstName: "The",
        lastName: "Goldfinch",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=The+Goldfinch",
      },
      genre: "Drama",
      pageCount: 258,
      cover: "https://covers.openlibrary.org/b/isbn/9780316055437-L.jpg",
      source: "Vintage",
      description:
        "A compelling story of drama with unforgettable characters and thrilling twists.",
    },
    {
      id: "10",
      title: "Circe",
      author: {
        id: "a10",
        firstName: "Circe",
        lastName: "Circe",
        nationality: "British",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Circe",
      },
      genre: "Adventure",
      pageCount: 259,
      cover: "https://covers.openlibrary.org/b/isbn/9780316556347-L.jpg",
      source: "Random House",
      description:
        "A compelling story of adventure with unforgettable characters and thrilling twists.",
    },
    {
      id: "11",
      title: "1984",
      author: {
        id: "a11",
        firstName: "1984",
        lastName: "1984",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=1984",
      },
      genre: "Fantasy",
      pageCount: 260,
      cover: "https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg",
      source: "Penguin",
      description:
        "A compelling story of fantasy with unforgettable characters and thrilling twists.",
    },
    {
      id: "12",
      title: "Pride and Prejudice",
      author: {
        id: "a12",
        firstName: "Pride",
        lastName: "Prejudice",
        nationality: "British",
        image:
          "https://api.dicebear.com/7.x/initials/svg?seed=Pride+and+Prejudice",
      },
      genre: "Science Fiction",
      pageCount: 261,
      cover: "https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg",
      source: "HarperCollins",
      description:
        "A compelling story of science fiction with unforgettable characters and thrilling twists.",
    },
    {
      id: "13",
      title: "The Hobbit",
      author: {
        id: "a13",
        firstName: "The",
        lastName: "Hobbit",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=The+Hobbit",
      },
      genre: "Historical Fiction",
      pageCount: 262,
      cover: "https://covers.openlibrary.org/b/isbn/9780547928227-L.jpg",
      source: "Faber & Faber",
      description:
        "A compelling story of historical fiction with unforgettable characters and thrilling twists.",
    },
    {
      id: "14",
      title: "To Kill a Mockingbird",
      author: {
        id: "a14",
        firstName: "To",
        lastName: "Mockingbird",
        nationality: "British",
        image:
          "https://api.dicebear.com/7.x/initials/svg?seed=To+Kill+a+Mockingbird",
      },
      genre: "Romance",
      pageCount: 263,
      cover: "https://covers.openlibrary.org/b/isbn/9780061120084-L.jpg",
      source: "Vintage",
      description:
        "A compelling story of romance with unforgettable characters and thrilling twists.",
    },
    {
      id: "15",
      title: "Dune",
      author: {
        id: "a15",
        firstName: "Dune",
        lastName: "Dune",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Dune",
      },
      genre: "Biography",
      pageCount: 264,
      cover: "https://covers.openlibrary.org/b/isbn/9780441013593-L.jpg",
      source: "Random House",
      description:
        "A compelling story of biography with unforgettable characters and thrilling twists.",
    },
    {
      id: "16",
      title: "The Girl on the Train",
      author: {
        id: "a16",
        firstName: "The",
        lastName: "Train",
        nationality: "British",
        image:
          "https://api.dicebear.com/7.x/initials/svg?seed=The+Girl+on+the+Train",
      },
      genre: "Memoir",
      pageCount: 265,
      cover: "https://covers.openlibrary.org/b/isbn/9781594634024-L.jpg",
      source: "Penguin",
      description:
        "A compelling story of memoir with unforgettable characters and thrilling twists.",
    },
    {
      id: "17",
      title: "Big Little Lies",
      author: {
        id: "a17",
        firstName: "Big",
        lastName: "Lies",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Big+Little+Lies",
      },
      genre: "Horror",
      pageCount: 266,
      cover: "https://covers.openlibrary.org/b/isbn/9780425274866-L.jpg",
      source: "HarperCollins",
      description:
        "A compelling story of horror with unforgettable characters and thrilling twists.",
    },
    {
      id: "18",
      title: "Sapiens",
      author: {
        id: "a18",
        firstName: "Sapiens",
        lastName: "Sapiens",
        nationality: "British",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Sapiens",
      },
      genre: "Thriller",
      pageCount: 267,
      cover: "https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg",
      source: "Faber & Faber",
      description:
        "A compelling story of thriller with unforgettable characters and thrilling twists.",
    },
    {
      id: "19",
      title: "The Catcher in the Rye",
      author: {
        id: "a19",
        firstName: "The",
        lastName: "Rye",
        nationality: "American",
        image:
          "https://api.dicebear.com/7.x/initials/svg?seed=The+Catcher+in+the+Rye",
      },
      genre: "Drama",
      pageCount: 268,
      cover: "https://covers.openlibrary.org/b/isbn/9780316769488-L.jpg",
      source: "Vintage",
      description:
        "A compelling story of drama with unforgettable characters and thrilling twists.",
    },
    {
      id: "20",
      title: "Brave New World",
      author: {
        id: "a20",
        firstName: "Brave",
        lastName: "World",
        nationality: "British",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Brave+New+World",
      },
      genre: "Adventure",
      pageCount: 269,
      cover: "https://covers.openlibrary.org/b/isbn/9780060850524-L.jpg",
      source: "Random House",
      description:
        "A compelling story of adventure with unforgettable characters and thrilling twists.",
    },
    {
      id: "25",
      title: "The Alchemist",
      author: {
        id: "a25",
        firstName: "Sally",
        lastName: "Rooney",
        nationality: "Irish",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Sally+Rooney",
      },
      genre: "Contemporary Fiction",
      pageCount: 567,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000024-L.jpg",
      source: "HarperCollins",
      description:
        "A heart-racing narrative that tests the limits of love, loss, and redemption.",
    },
    {
      id: "26",
      title: "The Book Thief",
      author: {
        id: "a26",
        firstName: "Brit",
        lastName: "Bennett",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Brit+Bennett",
      },
      genre: "Dystopian",
      pageCount: 536,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000025-L.jpg",
      source: "Simon & Schuster",
      description:
        "A heart-racing narrative that tests the limits of love, loss, and redemption.",
    },
    {
      id: "27",
      title: "Gone Girl",
      author: {
        id: "a27",
        firstName: "Michelle",
        lastName: "Obama",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Michelle+Obama",
      },
      genre: "Science Fiction",
      pageCount: 448,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000026-L.jpg",
      source: "St. Martin's Press",
      description:
        "An unforgettable journey through heartbreak, healing, and the resilience of the human spirit.",
    },
    {
      id: "28",
      title: "The Help",
      author: {
        id: "a28",
        firstName: "Margaret",
        lastName: "Atwood",
        nationality: "Canadian",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Margaret+Atwood",
      },
      genre: "Fantasy",
      pageCount: 343,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000027-L.jpg",
      source: "Bloomsbury",
      description:
        "A heart-racing narrative that tests the limits of love, loss, and redemption.",
    },
    {
      id: "29",
      title: "A Man Called Ove",
      author: {
        id: "a29",
        firstName: "Donna",
        lastName: "Tartt",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Donna+Tartt",
      },
      genre: "Science Fiction",
      pageCount: 476,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000028-L.jpg",
      source: "Riverhead Books",
      description:
        "Explores the complexity of identity and the search for truth in a fractured world.",
    },
    {
      id: "30",
      title: "Shantaram",
      author: {
        id: "a30",
        firstName: "Madeline",
        lastName: "Miller",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Madeline+Miller",
      },
      genre: "Fantasy",
      pageCount: 432,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000029-L.jpg",
      source: "St. Martin's Press",
      description:
        "Explores the complexity of identity and the search for truth in a fractured world.",
    },
    {
      id: "31",
      title: "The Kite Runner",
      author: {
        id: "a31",
        firstName: "Alex",
        lastName: "Michaelides",
        nationality: "British-Cypriot",
        image:
          "https://api.dicebear.com/7.x/initials/svg?seed=Alex+Michaelides",
      },
      genre: "Coming-of-Age",
      pageCount: 422,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000030-L.jpg",
      source: "Riverhead Books",
      description:
        "Explores the complexity of identity and the search for truth in a fractured world.",
    },
    {
      id: "32",
      title: "A Thousand Splendid Suns",
      author: {
        id: "a32",
        firstName: "Delia",
        lastName: "Owens",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Delia+Owens",
      },
      genre: "Coming-of-Age",
      pageCount: 597,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000031-L.jpg",
      source: "Random House",
      description:
        "A breathtaking blend of myth and modernity, weaving ancient magic with real emotion.",
    },
    {
      id: "33",
      title: "The Paris Library",
      author: {
        id: "a33",
        firstName: "Kristin",
        lastName: "Hannah",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Kristin+Hannah",
      },
      genre: "Psychological Thriller",
      pageCount: 328,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000032-L.jpg",
      source: "HarperCollins",
      description:
        "A vibrant depiction of a life lived on the margins, and the dreams that defy boundaries.",
    },
    {
      id: "34",
      title: "The Midnight Library",
      author: {
        id: "a34",
        firstName: "Tara",
        lastName: "Westover",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Tara+Westover",
      },
      genre: "Dystopian",
      pageCount: 544,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000033-L.jpg",
      source: "Random House",
      description:
        "An unforgettable journey through heartbreak, healing, and the resilience of the human spirit.",
    },
    {
      id: "35",
      title: "Project Hail Mary",
      author: {
        id: "a35",
        firstName: "Sally",
        lastName: "Rooney",
        nationality: "Irish",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Sally+Rooney",
      },
      genre: "Fantasy",
      pageCount: 257,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000034-L.jpg",
      source: "Crown",
      description:
        "A poignant exploration of what it means to belong\u2014and what it costs to stand apart.",
    },
    {
      id: "36",
      title: "Verity",
      author: {
        id: "a36",
        firstName: "Brit",
        lastName: "Bennett",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Brit+Bennett",
      },
      genre: "Contemporary Fiction",
      pageCount: 493,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000035-L.jpg",
      source: "Riverhead Books",
      description:
        "A portrait of a world on the brink, and the people who dare to challenge it.",
    },
    {
      id: "37",
      title: "Reminders of Him",
      author: {
        id: "a37",
        firstName: "Michelle",
        lastName: "Obama",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Michelle+Obama",
      },
      genre: "Dystopian",
      pageCount: 373,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000036-L.jpg",
      source: "St. Martin's Press",
      description:
        "A portrait of a world on the brink, and the people who dare to challenge it.",
    },
    {
      id: "38",
      title: "Ugly Love",
      author: {
        id: "a38",
        firstName: "Margaret",
        lastName: "Atwood",
        nationality: "Canadian",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Margaret+Atwood",
      },
      genre: "Dystopian",
      pageCount: 397,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000037-L.jpg",
      source: "HarperCollins",
      description:
        "Reveals the dark side of ambition and the cost of chasing perfection.",
    },
    {
      id: "39",
      title: "The Seven Husbands of Evelyn Hugo",
      author: {
        id: "a39",
        firstName: "Donna",
        lastName: "Tartt",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Donna+Tartt",
      },
      genre: "Literary Fiction",
      pageCount: 329,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000038-L.jpg",
      source: "Penguin Books",
      description:
        "An epic story that spans decades, illuminating the quiet strength of everyday heroes.",
    },
    {
      id: "40",
      title: "It Ends With Us",
      author: {
        id: "a40",
        firstName: "Madeline",
        lastName: "Miller",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Madeline+Miller",
      },
      genre: "Literary Fiction",
      pageCount: 304,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000039-L.jpg",
      source: "Random House",
      description:
        "A vibrant depiction of a life lived on the margins, and the dreams that defy boundaries.",
    },
    {
      id: "41",
      title: "It Starts With Us",
      author: {
        id: "a41",
        firstName: "Alex",
        lastName: "Michaelides",
        nationality: "British-Cypriot",
        image:
          "https://api.dicebear.com/7.x/initials/svg?seed=Alex+Michaelides",
      },
      genre: "Contemporary Fiction",
      pageCount: 600,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000040-L.jpg",
      source: "Random House",
      description:
        "A portrait of a world on the brink, and the people who dare to challenge it.",
    },
    {
      id: "42",
      title: "The House in the Cerulean Sea",
      author: {
        id: "a42",
        firstName: "Delia",
        lastName: "Owens",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Delia+Owens",
      },
      genre: "Coming-of-Age",
      pageCount: 521,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000041-L.jpg",
      source: "Penguin Books",
      description:
        "An epic story that spans decades, illuminating the quiet strength of everyday heroes.",
    },
    {
      id: "43",
      title: "The Song of Achilles",
      author: {
        id: "a43",
        firstName: "Kristin",
        lastName: "Hannah",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Kristin+Hannah",
      },
      genre: "Dystopian",
      pageCount: 305,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000042-L.jpg",
      source: "Penguin Books",
      description:
        "A breathtaking blend of myth and modernity, weaving ancient magic with real emotion.",
    },
    {
      id: "44",
      title: "Lessons in Chemistry",
      author: {
        id: "a44",
        firstName: "Tara",
        lastName: "Westover",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Tara+Westover",
      },
      genre: "Dystopian",
      pageCount: 266,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000043-L.jpg",
      source: "Riverhead Books",
      description:
        "Reveals the dark side of ambition and the cost of chasing perfection.",
    },
    {
      id: "45",
      title: "Tomorrow, and Tomorrow, and Tomorrow",
      author: {
        id: "a45",
        firstName: "Sally",
        lastName: "Rooney",
        nationality: "Irish",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Sally+Rooney",
      },
      genre: "Romance",
      pageCount: 414,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000044-L.jpg",
      source: "Simon & Schuster",
      description:
        "An epic story that spans decades, illuminating the quiet strength of everyday heroes.",
    },
    {
      id: "46",
      title: "The Love Hypothesis",
      author: {
        id: "a46",
        firstName: "Brit",
        lastName: "Bennett",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Brit+Bennett",
      },
      genre: "Science Fiction",
      pageCount: 316,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000045-L.jpg",
      source: "St. Martin's Press",
      description:
        "Explores the complexity of identity and the search for truth in a fractured world.",
    },
    {
      id: "47",
      title: "Fourth Wing",
      author: {
        id: "a47",
        firstName: "Michelle",
        lastName: "Obama",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Michelle+Obama",
      },
      genre: "Literary Fiction",
      pageCount: 531,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000046-L.jpg",
      source: "Riverhead Books",
      description:
        "A vibrant depiction of a life lived on the margins, and the dreams that defy boundaries.",
    },
    {
      id: "48",
      title: "Iron Flame",
      author: {
        id: "a48",
        firstName: "Margaret",
        lastName: "Atwood",
        nationality: "Canadian",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Margaret+Atwood",
      },
      genre: "Romance",
      pageCount: 508,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000047-L.jpg",
      source: "Random House",
      description:
        "A portrait of a world on the brink, and the people who dare to challenge it.",
    },
    {
      id: "49",
      title: "Throne of Glass",
      author: {
        id: "a49",
        firstName: "Donna",
        lastName: "Tartt",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Donna+Tartt",
      },
      genre: "Dystopian",
      pageCount: 412,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000048-L.jpg",
      source: "Penguin Books",
      description:
        "A gripping tale of secrets, lies, and the bonds that hold people together.",
    },
    {
      id: "50",
      title: "A Court of Thorns and Roses",
      author: {
        id: "a50",
        firstName: "Madeline",
        lastName: "Miller",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Madeline+Miller",
      },
      genre: "Psychological Thriller",
      pageCount: 358,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000049-L.jpg",
      source: "Crown",
      description:
        "An unforgettable journey through heartbreak, healing, and the resilience of the human spirit.",
    },
    {
      id: "51",
      title: "Empire of the Vampire",
      author: {
        id: "a51",
        firstName: "Alex",
        lastName: "Michaelides",
        nationality: "British-Cypriot",
        image:
          "https://api.dicebear.com/7.x/initials/svg?seed=Alex+Michaelides",
      },
      genre: "Psychological Thriller",
      pageCount: 527,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000050-L.jpg",
      source: "St. Martin's Press",
      description:
        "Explores the complexity of identity and the search for truth in a fractured world.",
    },
    {
      id: "52",
      title: "Priory of the Orange Tree",
      author: {
        id: "a52",
        firstName: "Delia",
        lastName: "Owens",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Delia+Owens",
      },
      genre: "Historical Fiction",
      pageCount: 468,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000051-L.jpg",
      source: "Simon & Schuster",
      description:
        "A heart-racing narrative that tests the limits of love, loss, and redemption.",
    },
    {
      id: "53",
      title: "Babel",
      author: {
        id: "a53",
        firstName: "Kristin",
        lastName: "Hannah",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Kristin+Hannah",
      },
      genre: "Coming-of-Age",
      pageCount: 449,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000052-L.jpg",
      source: "Bloomsbury",
      description:
        "A breathtaking blend of myth and modernity, weaving ancient magic with real emotion.",
    },
    {
      id: "54",
      title: "The Atlas Six",
      author: {
        id: "a54",
        firstName: "Tara",
        lastName: "Westover",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Tara+Westover",
      },
      genre: "Science Fiction",
      pageCount: 393,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000053-L.jpg",
      source: "HarperCollins",
      description:
        "An epic story that spans decades, illuminating the quiet strength of everyday heroes.",
    },
    {
      id: "55",
      title: "Red, White & Royal Blue",
      author: {
        id: "a55",
        firstName: "Sally",
        lastName: "Rooney",
        nationality: "Irish",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Sally+Rooney",
      },
      genre: "Romance",
      pageCount: 421,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000054-L.jpg",
      source: "Random House",
      description:
        "A heart-racing narrative that tests the limits of love, loss, and redemption.",
    },
    {
      id: "56",
      title: "Book Lovers",
      author: {
        id: "a56",
        firstName: "Brit",
        lastName: "Bennett",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Brit+Bennett",
      },
      genre: "Literary Fiction",
      pageCount: 489,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000055-L.jpg",
      source: "HarperCollins",
      description:
        "A breathtaking blend of myth and modernity, weaving ancient magic with real emotion.",
    },
    {
      id: "57",
      title: "People We Meet on Vacation",
      author: {
        id: "a57",
        firstName: "Michelle",
        lastName: "Obama",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Michelle+Obama",
      },
      genre: "Historical Fiction",
      pageCount: 281,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000056-L.jpg",
      source: "Bloomsbury",
      description:
        "A poignant exploration of what it means to belong\u2014and what it costs to stand apart.",
    },
    {
      id: "58",
      title: "Beach Read",
      author: {
        id: "a58",
        firstName: "Margaret",
        lastName: "Atwood",
        nationality: "Canadian",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Margaret+Atwood",
      },
      genre: "Psychological Thriller",
      pageCount: 419,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000057-L.jpg",
      source: "Riverhead Books",
      description:
        "Reveals the dark side of ambition and the cost of chasing perfection.",
    },
    {
      id: "59",
      title: "Happy Place",
      author: {
        id: "a59",
        firstName: "Donna",
        lastName: "Tartt",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Donna+Tartt",
      },
      genre: "Memoir",
      pageCount: 522,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000058-L.jpg",
      source: "Penguin Books",
      description:
        "A portrait of a world on the brink, and the people who dare to challenge it.",
    },
    {
      id: "60",
      title: "One Last Stop",
      author: {
        id: "a60",
        firstName: "Madeline",
        lastName: "Miller",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Madeline+Miller",
      },
      genre: "Fantasy",
      pageCount: 587,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000059-L.jpg",
      source: "Faber & Faber",
      description:
        "An epic story that spans decades, illuminating the quiet strength of everyday heroes.",
    },
    {
      id: "61",
      title: "The Inheritance Games",
      author: {
        id: "a61",
        firstName: "Alex",
        lastName: "Michaelides",
        nationality: "British-Cypriot",
        image:
          "https://api.dicebear.com/7.x/initials/svg?seed=Alex+Michaelides",
      },
      genre: "Psychological Thriller",
      pageCount: 474,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000060-L.jpg",
      source: "HarperCollins",
      description:
        "Explores the complexity of identity and the search for truth in a fractured world.",
    },
    {
      id: "62",
      title: "The Final Gambit",
      author: {
        id: "a62",
        firstName: "Delia",
        lastName: "Owens",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Delia+Owens",
      },
      genre: "Memoir",
      pageCount: 373,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000061-L.jpg",
      source: "Crown",
      description:
        "A breathtaking blend of myth and modernity, weaving ancient magic with real emotion.",
    },
    {
      id: "63",
      title: "The Hawthorne Legacy",
      author: {
        id: "a63",
        firstName: "Kristin",
        lastName: "Hannah",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Kristin+Hannah",
      },
      genre: "Fantasy",
      pageCount: 565,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000062-L.jpg",
      source: "Faber & Faber",
      description:
        "Reveals the dark side of ambition and the cost of chasing perfection.",
    },
    {
      id: "64",
      title: "Truly Devious",
      author: {
        id: "a64",
        firstName: "Tara",
        lastName: "Westover",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Tara+Westover",
      },
      genre: "Historical Fiction",
      pageCount: 282,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000063-L.jpg",
      source: "Random House",
      description:
        "An unforgettable journey through heartbreak, healing, and the resilience of the human spirit.",
    },
    {
      id: "65",
      title: "The Vanishing Stair",
      author: {
        id: "a65",
        firstName: "Sally",
        lastName: "Rooney",
        nationality: "Irish",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Sally+Rooney",
      },
      genre: "Fantasy",
      pageCount: 291,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000064-L.jpg",
      source: "Bloomsbury",
      description:
        "A portrait of a world on the brink, and the people who dare to challenge it.",
    },
    {
      id: "66",
      title: "The Hand on the Wall",
      author: {
        id: "a66",
        firstName: "Brit",
        lastName: "Bennett",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Brit+Bennett",
      },
      genre: "Memoir",
      pageCount: 548,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000065-L.jpg",
      source: "HarperCollins",
      description:
        "A heart-racing narrative that tests the limits of love, loss, and redemption.",
    },
    {
      id: "67",
      title: "A Good Girl's Guide to Murder",
      author: {
        id: "a67",
        firstName: "Michelle",
        lastName: "Obama",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Michelle+Obama",
      },
      genre: "Romance",
      pageCount: 534,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000066-L.jpg",
      source: "Random House",
      description:
        "A portrait of a world on the brink, and the people who dare to challenge it.",
    },
    {
      id: "68",
      title: "Good Girl, Bad Blood",
      author: {
        id: "a68",
        firstName: "Margaret",
        lastName: "Atwood",
        nationality: "Canadian",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Margaret+Atwood",
      },
      genre: "Contemporary Fiction",
      pageCount: 564,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000067-L.jpg",
      source: "HarperCollins",
      description:
        "A poignant exploration of what it means to belong\u2014and what it costs to stand apart.",
    },
    {
      id: "69",
      title: "As Good As Dead",
      author: {
        id: "a69",
        firstName: "Donna",
        lastName: "Tartt",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Donna+Tartt",
      },
      genre: "Memoir",
      pageCount: 431,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000068-L.jpg",
      source: "Bloomsbury",
      description:
        "A poignant exploration of what it means to belong\u2014and what it costs to stand apart.",
    },
    {
      id: "70",
      title: "The 5th Wave",
      author: {
        id: "a70",
        firstName: "Madeline",
        lastName: "Miller",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Madeline+Miller",
      },
      genre: "Coming-of-Age",
      pageCount: 475,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000069-L.jpg",
      source: "HarperCollins",
      description:
        "A breathtaking blend of myth and modernity, weaving ancient magic with real emotion.",
    },
    {
      id: "71",
      title: "The Infinite Sea",
      author: {
        id: "a71",
        firstName: "Alex",
        lastName: "Michaelides",
        nationality: "British-Cypriot",
        image:
          "https://api.dicebear.com/7.x/initials/svg?seed=Alex+Michaelides",
      },
      genre: "Dystopian",
      pageCount: 596,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000070-L.jpg",
      source: "Crown",
      description:
        "A portrait of a world on the brink, and the people who dare to challenge it.",
    },
    {
      id: "72",
      title: "The Last Star",
      author: {
        id: "a72",
        firstName: "Delia",
        lastName: "Owens",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Delia+Owens",
      },
      genre: "Literary Fiction",
      pageCount: 402,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000071-L.jpg",
      source: "Crown",
      description:
        "A poignant exploration of what it means to belong\u2014and what it costs to stand apart.",
    },
    {
      id: "73",
      title: "Scythe",
      author: {
        id: "a73",
        firstName: "Kristin",
        lastName: "Hannah",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Kristin+Hannah",
      },
      genre: "Memoir",
      pageCount: 570,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000072-L.jpg",
      source: "Penguin Books",
      description:
        "An unforgettable journey through heartbreak, healing, and the resilience of the human spirit.",
    },
    {
      id: "74",
      title: "Thunderhead",
      author: {
        id: "a74",
        firstName: "Tara",
        lastName: "Westover",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Tara+Westover",
      },
      genre: "Historical Fiction",
      pageCount: 371,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000073-L.jpg",
      source: "Bloomsbury",
      description:
        "A poignant exploration of what it means to belong\u2014and what it costs to stand apart.",
    },
    {
      id: "75",
      title: "The Toll",
      author: {
        id: "a75",
        firstName: "Sally",
        lastName: "Rooney",
        nationality: "Irish",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Sally+Rooney",
      },
      genre: "Contemporary Fiction",
      pageCount: 266,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000074-L.jpg",
      source: "Penguin Books",
      description:
        "A breathtaking blend of myth and modernity, weaving ancient magic with real emotion.",
    },
    {
      id: "76",
      title: "Legend",
      author: {
        id: "a76",
        firstName: "Brit",
        lastName: "Bennett",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Brit+Bennett",
      },
      genre: "Fantasy",
      pageCount: 395,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000075-L.jpg",
      source: "Crown",
      description:
        "A portrait of a world on the brink, and the people who dare to challenge it.",
    },
    {
      id: "77",
      title: "Prodigy",
      author: {
        id: "a77",
        firstName: "Michelle",
        lastName: "Obama",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Michelle+Obama",
      },
      genre: "Dystopian",
      pageCount: 398,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000076-L.jpg",
      source: "Random House",
      description:
        "A breathtaking blend of myth and modernity, weaving ancient magic with real emotion.",
    },
    {
      id: "78",
      title: "Champion",
      author: {
        id: "a78",
        firstName: "Margaret",
        lastName: "Atwood",
        nationality: "Canadian",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Margaret+Atwood",
      },
      genre: "Historical Fiction",
      pageCount: 328,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000077-L.jpg",
      source: "Faber & Faber",
      description:
        "A vibrant depiction of a life lived on the margins, and the dreams that defy boundaries.",
    },
    {
      id: "79",
      title: "Rebel",
      author: {
        id: "a79",
        firstName: "Donna",
        lastName: "Tartt",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Donna+Tartt",
      },
      genre: "Psychological Thriller",
      pageCount: 345,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000078-L.jpg",
      source: "Faber & Faber",
      description:
        "An unforgettable journey through heartbreak, healing, and the resilience of the human spirit.",
    },
    {
      id: "80",
      title: "Crescent City",
      author: {
        id: "a80",
        firstName: "Madeline",
        lastName: "Miller",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Madeline+Miller",
      },
      genre: "Coming-of-Age",
      pageCount: 474,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000079-L.jpg",
      source: "Random House",
      description:
        "A heart-racing narrative that tests the limits of love, loss, and redemption.",
    },
    {
      id: "81",
      title: "House of Earth and Blood",
      author: {
        id: "a81",
        firstName: "Alex",
        lastName: "Michaelides",
        nationality: "British-Cypriot",
        image:
          "https://api.dicebear.com/7.x/initials/svg?seed=Alex+Michaelides",
      },
      genre: "Historical Fiction",
      pageCount: 593,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000080-L.jpg",
      source: "HarperCollins",
      description:
        "A gripping tale of secrets, lies, and the bonds that hold people together.",
    },
    {
      id: "82",
      title: "House of Sky and Breath",
      author: {
        id: "a82",
        firstName: "Delia",
        lastName: "Owens",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Delia+Owens",
      },
      genre: "Literary Fiction",
      pageCount: 297,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000081-L.jpg",
      source: "Riverhead Books",
      description:
        "A heart-racing narrative that tests the limits of love, loss, and redemption.",
    },
    {
      id: "83",
      title: "Twilight",
      author: {
        id: "a83",
        firstName: "Kristin",
        lastName: "Hannah",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Kristin+Hannah",
      },
      genre: "Fantasy",
      pageCount: 263,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000082-L.jpg",
      source: "HarperCollins",
      description:
        "A vibrant depiction of a life lived on the margins, and the dreams that defy boundaries.",
    },
    {
      id: "84",
      title: "New Moon",
      author: {
        id: "a84",
        firstName: "Tara",
        lastName: "Westover",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Tara+Westover",
      },
      genre: "Historical Fiction",
      pageCount: 273,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000083-L.jpg",
      source: "Bloomsbury",
      description:
        "A gripping tale of secrets, lies, and the bonds that hold people together.",
    },
    {
      id: "85",
      title: "Eclipse",
      author: {
        id: "a85",
        firstName: "Sally",
        lastName: "Rooney",
        nationality: "Irish",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Sally+Rooney",
      },
      genre: "Historical Fiction",
      pageCount: 581,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000084-L.jpg",
      source: "Little, Brown and Company",
      description:
        "An unforgettable journey through heartbreak, healing, and the resilience of the human spirit.",
    },
    {
      id: "86",
      title: "Breaking Dawn",
      author: {
        id: "a86",
        firstName: "Brit",
        lastName: "Bennett",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Brit+Bennett",
      },
      genre: "Romance",
      pageCount: 454,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000085-L.jpg",
      source: "Crown",
      description:
        "A heart-racing narrative that tests the limits of love, loss, and redemption.",
    },
    {
      id: "87",
      title: "Midnight Sun",
      author: {
        id: "a87",
        firstName: "Michelle",
        lastName: "Obama",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Michelle+Obama",
      },
      genre: "Memoir",
      pageCount: 270,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000086-L.jpg",
      source: "Faber & Faber",
      description:
        "A portrait of a world on the brink, and the people who dare to challenge it.",
    },
    {
      id: "88",
      title: "The Maze Runner",
      author: {
        id: "a88",
        firstName: "Margaret",
        lastName: "Atwood",
        nationality: "Canadian",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Margaret+Atwood",
      },
      genre: "Contemporary Fiction",
      pageCount: 430,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000087-L.jpg",
      source: "Little, Brown and Company",
      description:
        "A heart-racing narrative that tests the limits of love, loss, and redemption.",
    },
    {
      id: "89",
      title: "The Scorch Trials",
      author: {
        id: "a89",
        firstName: "Donna",
        lastName: "Tartt",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Donna+Tartt",
      },
      genre: "Psychological Thriller",
      pageCount: 580,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000088-L.jpg",
      source: "St. Martin's Press",
      description:
        "A portrait of a world on the brink, and the people who dare to challenge it.",
    },
    {
      id: "90",
      title: "The Death Cure",
      author: {
        id: "a90",
        firstName: "Madeline",
        lastName: "Miller",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Madeline+Miller",
      },
      genre: "Fantasy",
      pageCount: 350,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000089-L.jpg",
      source: "St. Martin's Press",
      description:
        "A gripping tale of secrets, lies, and the bonds that hold people together.",
    },
    {
      id: "91",
      title: "The Kill Order",
      author: {
        id: "a91",
        firstName: "Alex",
        lastName: "Michaelides",
        nationality: "British-Cypriot",
        image:
          "https://api.dicebear.com/7.x/initials/svg?seed=Alex+Michaelides",
      },
      genre: "Coming-of-Age",
      pageCount: 538,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000090-L.jpg",
      source: "Penguin Books",
      description:
        "A poignant exploration of what it means to belong\u2014and what it costs to stand apart.",
    },
    {
      id: "92",
      title: "The Ballad of Songbirds and Snakes",
      author: {
        id: "a92",
        firstName: "Delia",
        lastName: "Owens",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Delia+Owens",
      },
      genre: "Psychological Thriller",
      pageCount: 320,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000091-L.jpg",
      source: "St. Martin's Press",
      description:
        "A breathtaking blend of myth and modernity, weaving ancient magic with real emotion.",
    },
    {
      id: "93",
      title: "Mockingjay",
      author: {
        id: "a93",
        firstName: "Kristin",
        lastName: "Hannah",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Kristin+Hannah",
      },
      genre: "Coming-of-Age",
      pageCount: 459,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000092-L.jpg",
      source: "Crown",
      description:
        "A poignant exploration of what it means to belong\u2014and what it costs to stand apart.",
    },
    {
      id: "94",
      title: "Catching Fire",
      author: {
        id: "a94",
        firstName: "Tara",
        lastName: "Westover",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Tara+Westover",
      },
      genre: "Romance",
      pageCount: 316,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000093-L.jpg",
      source: "Little, Brown and Company",
      description:
        "An unforgettable journey through heartbreak, healing, and the resilience of the human spirit.",
    },
    {
      id: "95",
      title: "The Hunger Games",
      author: {
        id: "a95",
        firstName: "Sally",
        lastName: "Rooney",
        nationality: "Irish",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Sally+Rooney",
      },
      genre: "Dystopian",
      pageCount: 366,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000094-L.jpg",
      source: "Faber & Faber",
      description:
        "A poignant exploration of what it means to belong\u2014and what it costs to stand apart.",
    },
    {
      id: "96",
      title: "An Ember in the Ashes",
      author: {
        id: "a96",
        firstName: "Brit",
        lastName: "Bennett",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Brit+Bennett",
      },
      genre: "Fantasy",
      pageCount: 290,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000095-L.jpg",
      source: "HarperCollins",
      description:
        "An unforgettable journey through heartbreak, healing, and the resilience of the human spirit.",
    },
    {
      id: "97",
      title: "A Torch Against the Night",
      author: {
        id: "a97",
        firstName: "Michelle",
        lastName: "Obama",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Michelle+Obama",
      },
      genre: "Contemporary Fiction",
      pageCount: 344,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000096-L.jpg",
      source: "Penguin Books",
      description:
        "A heart-racing narrative that tests the limits of love, loss, and redemption.",
    },
    {
      id: "98",
      title: "A Reaper at the Gates",
      author: {
        id: "a98",
        firstName: "Margaret",
        lastName: "Atwood",
        nationality: "Canadian",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Margaret+Atwood",
      },
      genre: "Contemporary Fiction",
      pageCount: 408,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000097-L.jpg",
      source: "Simon & Schuster",
      description:
        "A gripping tale of secrets, lies, and the bonds that hold people together.",
    },
    {
      id: "99",
      title: "A Sky Beyond the Storm",
      author: {
        id: "a99",
        firstName: "Donna",
        lastName: "Tartt",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Donna+Tartt",
      },
      genre: "Fantasy",
      pageCount: 486,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000098-L.jpg",
      source: "Penguin Books",
      description:
        "A breathtaking blend of myth and modernity, weaving ancient magic with real emotion.",
    },
    {
      id: "100",
      title: "The Silent Patient",
      author: {
        id: "a100",
        firstName: "Madeline",
        lastName: "Miller",
        nationality: "American",
        image: "https://api.dicebear.com/7.x/initials/svg?seed=Madeline+Miller",
      },
      genre: "Coming-of-Age",
      pageCount: 543,
      cover: "https://covers.openlibrary.org/b/isbn/9780000000099-L.jpg",
      source: "Faber & Faber",
      description:
        "A portrait of a world on the brink, and the people who dare to challenge it.",
    },
  ],
};
/*{
      id: "1",
      title: "The Silent Patient",
      author: {
        id: "a1",
        firstName: "The",
        lastName: "Patient",
        nationality: "American",
        image:
          "https://api.dicebear.com/7.x/initials/svg?seed=The+Silent+Patient",
      },
      genre: "Fantasy",
      pageCount: 250,
      cover: "https://covers.openlibrary.org/b/isbn/9781250301697-L.jpg",
      source: "Penguin",
      description:
        "A compelling story of fantasy with unforgettable characters and thrilling twists.",
    }*/
const authors = [
  ...new Map(
    jsonData.books.map((book) => [book.author.id, book.author])
  ).values(),
];
const books = jsonData.books.map((book) => ({
  id: book.id,
  title: book.title,
  author_id: book.author.id,
  genre: book.genre,
  page_count: book.pageCount,
  cover: book.cover,
  source: book.source,
  description: book.description,
}));
fs.writeFileSync(
  path.join(__dirname, "books.json"),
  JSON.stringify(books, null, 2)
);
fs.writeFileSync(
  path.join(__dirname, "authors.json"),
  JSON.stringify(authors, null, 2)
);
